kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: sireax/rtk-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 500Mi
              cpu: "1"
            requests:
              memory: 500Mi
              cpu: "1"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000